### ISSUE TITLE
Protocol doc page is 404

### ISSUE THREAD

**Issue by johnwlockwood** [nats-io/nats-docs#26]
The link to the protocol documentation, http://nats.io/internals/nats-protocol/#CONNECT, on http://nats.io/documentation/internals/nats-guide/ gets a 404 error.

**Comment by lparis** [comment]
Closing. This appears to be fixed in the current deploy of the docs: http://nats.io/documentation/internals/nats-guide/. The proper link is http://nats.io/documentation/internals/nats-protocol/#CONNECT.
