### ISSUE TITLE
Clarify the protocol or create issues in clients/gnatsd?

### ISSUE THREAD

**Issue by camros** [nats-io/nats-docs#31]
There needs to be clarity around the following:
1. Termination sequence... Is it a carriage return, new line or just new line, or either? Gnatsd allows either. 
2. The treatment of free standing carriage returns needs clarified. There is a bug or feature in gnatsd now depending on this and clients that allows  carriage return without a following new line and then removes 1 from the buffer even if the previous char was not a new line. 
3. Some verbs allow white pace after the last optional argument and some do not. Need clarity. 
4. Character sets are not mentioned anywhere but most of the code only currently supports ASCII and other eight byte sets. Need clarify and enforcement possibly before users want to use a utf/multi-byte subject name. 
5. Clarify the semantics of ping and pong. Currently gnatsd and some clients use ping/pong to optimize state transitions. We need something like this somewhere: Some client and server implementations may send PING messages and expect PONG responses to synchronize (need better wording) certain states. For example directly after a client handshake with gnatsd (CONNECT/INFO) some clients may send a PING message and require a PONG response for the handshake to be semantically complete. All client and server implementations _should_ therefor, send a PONG response with the minimum amount of clock time/latency as possible to avoid such clients and servers from blocking. 

These are grouped for now. We should discuss and we can regroup, etc.

**Comment by camros** [comment]
There needs to be clarity sound the following:
1. Termination sequence,cigs it a carriage return, new line or just new line, or either? Gnatsd allows either. 
2. The treatment of free standing carriage returns needs clarified. There is a bug or feature in gnatsd now depending on this and clients that allows  carriage return without a following new line and then removes 1 from the buffer even if the previous char was not a new line. 
3. Some verbs allow white pace after the last optional argument and some do not. Need clarity. 
4. Character s to are not mentioned anywhere but the code only currently supports ASCII and other eight byte sets need clarify and enforcement possibly before users want to use a utf subject name. 

These are grouped for now.lets discuss and we can I group, etc.

**Comment by derekcollison** [comment]
For all protocols, CR/LF (\r\n) denote a marker to interpret. This terminates a control line. This is even true for message payloads, either PUB or MSG, with a control line denoting a message. The payload is opaque, and the protocol engine will simply skip N bytes after receiving a PUB (from client) or MSG (to client).

**Comment by derekcollison** [comment]
For 3, the server protocol parser can tolerate extra spaces anywhere. For clients it depends, but even the regex based parsers can do so I believe. At least the ones I wrote or co-authored.

**Comment by derekcollison** [comment]
for 4, the protocol is ASCII, payloads are opaque and can be any encoding a client can understand, e.g. UTF8.

**Comment by derekcollison** [comment]
For 5, PING/PONG pairs can be sent by the server or a client. Any side receiving a PING simply responds with a PONG. Clients can use higher semantics to do flush based closures, etc.

**Comment by mcqueary** [comment]
Re #5, I don't believe PING and PONG should have any higher meaning in the protocol document itself. In the "client guide", we can certainly document cases where it makes sense to PING/PONG, using examples from the Apcera-supported clients, e.g. how we currently do `flush()` operations. However, that's advice, not specifying the meaning of the protocol.

**Comment by derekcollison** [comment]
Agree, was for clarity for Jeff.
