### ISSUE TITLE
Add "Edit on GitHub" button/link

### ISSUE THREAD

**Issue by mcqueary** [nats-io/nats-docs#34]
To make editing/contributing easier, many sites add an "Edit on GitHub" button/link on every page, which takes them straight to that page in the GitHub editor, allowing them to make a quick fix and generate a PR. We should also have that.

Here's an example (see top right): 
http://read-the-docs.readthedocs.org/en/latest/builds.html

/cc @derekcollison @chriscasper @lparis

**Comment by derekcollison** [comment]
+1

**Comment by mcqueary** [comment]
Closed by #43
