### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by yuce** [nats-io/nats-docs#37]
In [protocol docs](http://nats.io/documentation/internals/nats-protocol), it is mentioned that subject names are case insensitive:

> Subject names, including reply subject (INBOX) names, are case-insensitive ...

This led me to believe that subjects `foo.bar` and `FOO.BAR` must be equivalent. But that's not the case on `demo.nats.io`:

Terminal 1:

    Connected to demo.nats.io.
    Escape character is '^]'.
    INFO {"server_id":"a94186ed5c29e1a70b8b513cd3b33c8c","version":"0.7.2","go":"go1.5.2","host":"0.0.0.0","port":4222,"auth_required":false,"ssl_required":false,"tls_required":false,"tls_verify":false,"max_payload":1048576} 
    SUB foo.bar 1
    +OK

Terminal 2

    Connected to demo.nats.io.
    Escape character is '^]'.
    INFO {"server_id":"a94186ed5c29e1a70b8b513cd3b33c8c","version":"0.7.2","go":"go1.5.2","host":"0.0.0.0","port":4222,"auth_required":false,"ssl_required":false,"tls_required":false,"tls_verify":false,"max_payload":1048576} 
    PUB FOO.BAR 0
    
    +OK

No `MSG` is received in Terminal 1.

How about message names? In [protocol docs](http://nats.io/documentation/internals/nats-protocol) there is no mention about case sensitivity of them, so I would think they are case sensitive; but apparently they are not:

    Connected to demo.nats.io.
    Escape character is '^]'.
    INFO {"server_id":"a94186ed5c29e1a70b8b513cd3b33c8c","version":"0.7.2","go":"go1.5.2","host":"0.0.0.0","port":4222,"auth_required":false,"ssl_required":false,"tls_required":false,"tls_verify":false,"max_payload":1048576} 
    pub abc 0

    +OK

As far as I've read its source, Elixir client only recognizes upper case message names..

It would be great to get a clarification about case sensitivity. Sorry if this should have gone to the gnatsd ad/or Elixir tracker.

**Comment by mcqueary** [comment]
Hi, your conclusions are correct -- subject names are case sensitive and protocol OPs are not. Thanks for pointing out the error re: subject names.
