### ISSUE TITLE
Protocol demo inconsistent about SUB args

### ISSUE THREAD

**Issue by banks** [nats-io/nats-docs#40]
The protocol demo in step 3 says:

> On the wildcard subject foo.* with message size limit of 90 bytes.
>   sub foo.* 90

But the protocol docs clearly state that the last argument to `sub` is `sid` not a messsage size limit.

In fact it's very obvious this is the case if you try it - setting it to 1 does not prevent messages greater than 1 byte being delivered...

Minor detail, but wanted to report it while I saw it.

**Comment by mcqueary** [comment]
Thanks, there were actually a couple of similar errors in there as well, which I've corrected.
